### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by IT-Tagore** [boehs/Lightly#14]
my device info:
Operating System: openSUSE Tumbleweed 20240110
KDE Plasma Version: 6.0.80
KDE Frameworks Version: 5.249.0
Qt Version: 6.6.1
Kernel Version: 6.6.10-1-default (64-bit)
Graphics Platform: Wayland

```
cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_LIBDIR=lib64 -DBUILD_TESTING=OFF ..
```

error info:
CMake Error at /usr/lib64/cmake/Qt6Core/Qt6CoreVersionlessTargets.cmake:42 (message):
  Some (but not all) targets in this export set were already defined.

  Targets Defined: Qt::Core

  Targets not yet defined: Qt::CorePrivate

Call Stack (most recent call first):
  /usr/lib64/cmake/Qt6Core/Qt6CoreConfig.cmake:68 (include)
  /usr/share/cmake/Modules/CMakeFindDependencyMacro.cmake:76 (find_package)
  /usr/lib64/cmake/Qt6/QtPublicDependencyHelpers.cmake:111 (find_dependency)
  /usr/lib64/cmake/Qt6Gui/Qt6GuiDependencies.cmake:39 (_qt_internal_find_qt_dependencies)
  /usr/lib64/cmake/Qt6Gui/Qt6GuiConfig.cmake:50 (include)
  /usr/share/cmake/Modules/CMakeFindDependencyMacro.cmake:76 (find_package)
  /usr/lib64/cmake/KDecoration2/KDecoration2Config.cmake:38 (find_dependency)
  CMakeLists.txt:25 (find_package)

CMake Error at /usr/share/cmake/Modules/CMakeFindDependencyMacro.cmake:76 (find_package):
  Found package configuration file:

    /usr/lib64/cmake/Qt6Gui/Qt6GuiConfig.cmake

  but it set Qt6Gui_FOUND to FALSE so package "Qt6Gui" is considered to be
  NOT FOUND.
Call Stack (most recent call first):
  /usr/lib64/cmake/KDecoration2/KDecoration2Config.cmake:38 (find_dependency)
  CMakeLists.txt:25 (find_package)

**Comment by IT-Tagore** [comment]
thanks for you

**Comment by boehs** [comment]
This package has not been yet ported to qt6
