### ISSUE TITLE
How To Build On OpenSUSE Tumbleweed Plasma 6

### ISSUE THREAD

**Issue by Nano-Ocelot** [boehs/Lightly#21]
The requirements are outdated showing the build requirements for Plasma 5 and I can't figure out what is required for building for Plasma 6.

**Comment by Nano-Ocelot** [comment]
Still getting this error after installing those.

```
CMake Error at /usr/lib64/cmake/Qt6Core/Qt6CoreVersionlessTargets.cmake:42 (message):
  Some (but not all) targets in this export set were already defined.

  Targets Defined: Qt::Core

  Targets not yet defined: Qt::CorePrivate

Call Stack (most recent call first):
  /usr/lib64/cmake/Qt6Core/Qt6CoreConfig.cmake:68 (include)
  /usr/share/cmake/Modules/CMakeFindDependencyMacro.cmake:76 (find_package)
  /usr/lib64/cmake/Qt6/QtPublicDependencyHelpers.cmake:111 (find_dependency)
  /usr/lib64/cmake/Qt6Gui/Qt6GuiDependencies.cmake:39 (_qt_internal_find_qt_dependencies)
  /usr/lib64/cmake/Qt6Gui/Qt6GuiConfig.cmake:50 (include)
  /usr/share/cmake/Modules/CMakeFindDependencyMacro.cmake:76 (find_package)
  /usr/lib64/cmake/KDecoration2/KDecoration2Config.cmake:38 (find_dependency)
  CMakeLists.txt:25 (find_package)


CMake Error at /usr/share/cmake/Modules/CMakeFindDependencyMacro.cmake:76 (find_package):
  Found package configuration file:

    /usr/lib64/cmake/Qt6Gui/Qt6GuiConfig.cmake

  but it set Qt6Gui_FOUND to FALSE so package "Qt6Gui" is considered to be
  NOT FOUND.
Call Stack (most recent call first):
  /usr/lib64/cmake/KDecoration2/KDecoration2Config.cmake:38 (find_dependency)
  CMakeLists.txt:25 (find_package)


-- Configuring incomplete, errors occurred!
```

**Comment by kturques** [comment]
kcmutils from KDE6 is kf6-kcmutils-devel

I've compiled with these packages installed:
kf6-extra-cmake-modules qt6-base-devel kf6-kcoreaddons-devel kf6-kcolorscheme-devel kf6-kconfig-devel kf6-kguiaddons-devel kf6-ki18n-devel kf6-kiconthemes-devel kf6-kwindowsystem-devel kdecoration6-devel kf6-kcmutils-devel qt6-quick-devel kf6-kirigami-devel kf6-frameworkintegration-devel

**Comment by kturques** [comment]
**Full build process:**

# Requirements
zypper in --no-recommends git ninja cmake kf6-extra-cmake-modules qt6-base-devel kf6-kcoreaddons-devel kf6-kcolorscheme-devel kf6-kconfig-devel kf6-kguiaddons-devel kf6-ki18n-devel kf6-kiconthemes-devel kf6-kwindowsystem-devel kdecoration6-devel kf6-kcmutils-devel qt6-quick-devel kf6-kirigami-devel kf6-frameworkintegration-devel

# Clone qt6 branch
`git clone -b qt6 --single-branch --depth 1 https://github.com/boehs/Lightly`

# Apply [patch1.txt](https://github.com/boehs/Lightly/files/14723005/patch1.txt) restoring [missing files](https://github.com/boehs/Lightly/issues/13#issuecomment-1974016287) :
```
cd Lightly
patch -Np1 -i patch1.txt
```
# Build
```
cmake -G Ninja -S . -B ./build -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF -DCMAKE_INSTALL_LIBDIR=lib64 -DCMAKE_INSTALL_PREFIX=/usr

cmake --build ./build --parallel
```
# Install
`DESTDIR=./installfiles cmake --install ./build`
OR
`sudo cmake --install ./build`

**Comment by Nano-Ocelot** [comment]
Worked like a charm. Thank you so much.

**Comment by Nano-Ocelot** [comment]
That worked for me. Thanks a bunch.

**Comment by hrqmonteiro** [comment]
> #### Requirements
> 
> `sudo zypper in --no-recommends git ninja cmake kf6-extra-cmake-modules qt6-base-devel kf6-kcoreaddons-devel kf6-kcolorscheme-devel kf6-kconfig-devel kf6-kguiaddons-devel kf6-ki18n-devel kf6-kiconthemes-devel kf6-kwindowsystem-devel kdecoration6-devel kf6-kcmutils-devel qt6-quick-devel kf6-kirigami-devel kf6-frameworkintegration-devel`
> #### Clone qt6 branch
> 
> `git clone -b qt6 --single-branch --depth 1 https://github.com/boehs/Lightly`
> #### Apply [patch1.txt](https://github.com/boehs/Lightly/files/14723005/patch1.txt) ro restore the [missing files](https://github.com/boehs/Lightly/issues/13#issuecomment-1974016287) :
> 
> `cd Lightly` `patch -Np1 -i patch1.txt`
> #### Build
> 
> `cmake -G Ninja -S . -B ./build -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF -DCMAKE_INSTALL_LIBDIR=lib64 -DCMAKE_INSTALL_PREFIX=/usr`
> 
> `cmake --build ./build --parallel`
> #### Install
> 
> `DESTDIR=./installfiles cmake --install ./build` OR `sudo cmake --install ./build`

Did that but it doesn't appear on the Application Style list:
![image](https://github.com/boehs/Lightly/assets/17055027/f51ca9d7-d642-4846-975e-e27696dce565)

**Comment by hrqmonteiro** [comment]
It only appears in Colors, but not on Application Style

![image](https://github.com/boehs/Lightly/assets/17055027/d5b6c3f1-7e1d-45ef-9e13-9c7e487c1bca)

**Comment by hrqmonteiro** [comment]
Now, on a fresh install, it does not appear on anything

Will you please update the help to install? 

> #### Requirements
> 
> `sudo zypper in --no-recommends git ninja cmake kf6-extra-cmake-modules qt6-base-devel kf6-kcoreaddons-devel kf6-kcolorscheme-devel kf6-kconfig-devel kf6-kguiaddons-devel kf6-ki18n-devel kf6-kiconthemes-devel kf6-kwindowsystem-devel kdecoration6-devel kf6-kcmutils-devel qt6-quick-devel kf6-kirigami-devel kf6-frameworkintegration-devel`
> #### Clone qt6 branch
> 
> `git clone -b qt6 --single-branch --depth 1 https://github.com/boehs/Lightly`
> #### Apply [patch1.txt](https://github.com/boehs/Lightly/files/14723005/patch1.txt) ro restore the [missing files](https://github.com/boehs/Lightly/issues/13#issuecomment-1974016287) :
> 
> `cd Lightly` `patch -Np1 -i patch1.txt`
> #### Build
> 
> `cmake -G Ninja -S . -B ./build -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF -DCMAKE_INSTALL_LIBDIR=lib64 -DCMAKE_INSTALL_PREFIX=/usr`
> 
> `cmake --build ./build --parallel`
> #### Install
> 
> `DESTDIR=./installfiles cmake --install ./build` OR `sudo cmake --install ./build`


It's been like 8 months since we are asking for help
