### ISSUE TITLE
Mention AUR package

### ISSUE THREAD

**Issue by DexterHaxxor** [boehs/Lightly#5]
Hello, I just created the https://aur.archlinux.org/packages/lightly-boehs-git package on the Arch User Repository. Would you consider mentioning it in the readme to simply the installation process for Arch users?

**Comment by boehs** [comment]
Thank you. I will test this in a couple days when I get back to my linux box and then add it to the readme

**Comment by DexterHaxxor** [comment]
Any progress on this?

**Comment by Webblitchy** [comment]
> Any progress on this?

Maybe you should update dependencies (with their new names) first.
@DexterHaxxor

**Comment by DexterHaxxor** [comment]
Will do.

**Comment by boehs** [comment]
lightly-git has shockingly switched to using my fork so I will close this now
