### ISSUE TITLE
Failed to apply the selected style: "Lightly".

### ISSUE THREAD

**Issue by Octopus1348** [boehs/Lightly#6]
I get this error when trying to apply the theme: Failed to apply the selected style: "Lightly".

**Comment by kturques** [comment]
https://github.com/boehs/Lightly/issues/4
Same problem as above? Using Opensuse or Fedora? Try building with:
`cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_LIBDIR=lib64 -DBUILD_TESTING=OFF ..`

**Comment by Octopus1348** [comment]
Yes. It works now.
